export const SET_USER_INFO = 'SET_USER_INFO'
export const REMOVE_USER_INFO = 'REMOVE_USER_INFO'

export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN'

export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN'
export const REMOVE_REFRESH_TOKEN = 'REMOVE_REFRESH_TOKEN'